# Generated by Django 5.0.6 on 2024-06-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCurso', models.CharField(max_length=10, verbose_name='ID Curso')),
                ('nombreCurso', models.TextField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='Imagen', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
