# Generated by Django 5.0.6 on 2024-06-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='id',
        ),
        migrations.AddField(
            model_name='curso',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(verbose_name='Añade una descripción'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='idCurso',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombreCurso',
            field=models.CharField(max_length=200, verbose_name='Nombre del Curso'),
        ),
    ]
