# Generated by Django 5.0.6 on 2024-06-25 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_remove_curso_id_curso_fechainicio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['created'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('claveActividad', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Clave Actividad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('nombreCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso', verbose_name='Nombre del Curso')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fechaCreacion'],
            },
        ),
    ]
