# Generated by Django 5.0.6 on 2024-06-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_actividad_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Imagen'),
        ),
    ]
