# Generated by Django 5.0.6 on 2024-06-25 04:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_comentariocontacto_alter_alumnos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='coment',
            field=ckeditor.fields.RichTextField(verbose_name='Comentario'),
        ),
    ]
